server:
  port: 8081
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  messages:
    basename: i18n/messages
    cache-second: 3600
    encoding: UTF-8
#日志级别
logging:
  level:
    com.zhonghui: debug
#是否开启 swagger-ui
swagger:
  enabled: true

# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/com.zhonghui.mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
#监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

product:
  licensePath:
  company: 成都中慧
  url: https://license.zhonghui.vip/prod-api
  #url: http://localhost:8081